baseURL = 'https://itsmonish.pages.dev/'
languageCode = 'en-us'
enableRobotsTXT = true
title = "Monish Kumar's Blog"

theme = "hugo-theme-stack"

[params]
description = "Personal page and blog about CTF and technical writeups. Covers topics such as Cybersecurity, Linux and more"

[caches]
[caches.images]
dir = ':cacheDir/images'

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
